package com.tracker.ui.transactions

import android.content.Context
import android.print.PrintAttributes
import android.print.PrintManager
import android.webkit.WebView
import android.webkit.WebViewClient
import com.tracker.domain.model.Transaction
import com.tracker.domain.model.TransactionType
import java.text.SimpleDateFormat
import java.time.YearMonth
import java.time.format.DateTimeFormatter
import java.util.Date
import java.util.Locale

object TransactionReportPrinter {
    fun print(
        context: Context,
        month: YearMonth,
        transactions: List<Transaction>,
        currencyCode: String
    ) {
        val monthLabel = month.format(DateTimeFormatter.ofPattern("MMMM yyyy"))
        val dateFormat = SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault())
        val income = transactions.filter { it.type == TransactionType.IN }.sumOf { it.amount }
        val expense = transactions.filter { it.type == TransactionType.OUT }.sumOf { it.amount }

        val rows = transactions.joinToString("") { transaction ->
            """
            <tr>
              <td>${dateFormat.format(Date(transaction.date)).html()}</td>
              <td>${transaction.description.html()}<small>${transaction.category.html()} · ${transaction.paymentMethod.html()}</small></td>
              <td class="${if (transaction.type == TransactionType.IN) "income" else "expense"}">
                ${if (transaction.type == TransactionType.IN) "+" else "-"}${money(transaction.amount, currencyCode)}
              </td>
            </tr>
            """.trimIndent()
        }

        val html = """
            <!doctype html>
            <html><head><meta charset="utf-8"><style>
              @page { margin: 18mm; }
              body { font-family: sans-serif; color: #172033; font-size: 12px; }
              .header { display: flex; justify-content: space-between; align-items: end; border-bottom: 3px solid #4f46e5; padding-bottom: 14px; }
              h1 { margin: 0; font-size: 25px; } h2 { color: #667085; font-size: 14px; margin: 5px 0 0; font-weight: normal; }
              .summary { display: flex; gap: 12px; margin: 20px 0; }
              .box { flex: 1; background: #f4f7ff; border: 1px solid #e3e7f2; border-radius: 10px; padding: 12px; }
              .box b { display: block; font-size: 18px; margin-top: 5px; }
              table { width: 100%; border-collapse: collapse; }
              th { text-align: left; color: #667085; font-size: 10px; text-transform: uppercase; padding: 9px 8px; border-bottom: 1px solid #d7dce8; }
              td { padding: 11px 8px; border-bottom: 1px solid #eceff5; vertical-align: top; }
              td:last-child, th:last-child { text-align: right; white-space: nowrap; font-weight: bold; }
              small { display: block; color: #98a2b3; margin-top: 3px; }
              .income { color: #059669; } .expense { color: #e11d48; }
              .empty { text-align: center; color: #667085; padding: 40px; }
              footer { margin-top: 20px; color: #98a2b3; font-size: 10px; }
            </style></head><body>
              <div class="header"><div><h1>Money mutation report</h1><h2>$monthLabel</h2></div><b>${transactions.size} records</b></div>
              <div class="summary">
                <div class="box">Income<b class="income">+${money(income, currencyCode)}</b></div>
                <div class="box">Expense<b class="expense">-${money(expense, currencyCode)}</b></div>
                <div class="box">Net movement<b>${signedMoney(income - expense, currencyCode)}</b></div>
              </div>
              ${if (transactions.isEmpty()) "<div class=\"empty\">No mutations for this month.</div>" else """
              <table><thead><tr><th>Date</th><th>Mutation</th><th>Amount</th></tr></thead><tbody>$rows</tbody></table>
              """}
              <footer>Generated by Money Tracker · $monthLabel</footer>
            </body></html>
        """.trimIndent()

        val webView = WebView(context)
        webView.webViewClient = object : WebViewClient() {
            override fun onPageFinished(view: WebView, url: String?) {
                val manager = context.getSystemService(Context.PRINT_SERVICE) as PrintManager
                manager.print(
                    "Money Tracker - $monthLabel",
                    view.createPrintDocumentAdapter("Mutations $monthLabel"),
                    PrintAttributes.Builder()
                        .setMediaSize(PrintAttributes.MediaSize.ISO_A4)
                        .setColorMode(PrintAttributes.COLOR_MODE_COLOR)
                        .build()
                )
            }
        }
        webView.loadDataWithBaseURL(null, html, "text/HTML", "UTF-8", null)
    }

    private fun money(cents: Long, currencyCode: String): String {
        val symbol = runCatching { java.util.Currency.getInstance(currencyCode).symbol }
            .getOrDefault(currencyCode)
        return "$symbol ${String.format(Locale.getDefault(), "%,d.%02d", cents / 100, kotlin.math.abs(cents % 100))}"
    }

    private fun signedMoney(cents: Long, currencyCode: String): String =
        "${if (cents >= 0) "+" else "-"}${money(kotlin.math.abs(cents), currencyCode)}"

    private fun String.html(): String = replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
}
