-- Money Tracker remote persistence
-- Run with `supabase db push`, or paste into the Supabase SQL editor.

create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    type text not null check (type in ('IN', 'OUT')),
    amount bigint not null check (amount > 0),
    description text not null check (char_length(description) between 1 and 160),
    date bigint not null,
    category text not null check (char_length(category) between 1 and 60),
    payment_method text not null check (char_length(payment_method) between 1 and 60),
    created_at bigint not null default ((extract(epoch from now()) * 1000)::bigint)
);

create index if not exists transactions_user_date_idx
    on public.transactions (user_id, date desc);

alter table public.transactions enable row level security;

drop policy if exists "Users can read their transactions" on public.transactions;
create policy "Users can read their transactions"
    on public.transactions for select
    to authenticated
    using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their transactions" on public.transactions;
create policy "Users can create their transactions"
    on public.transactions for insert
    to authenticated
    with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their transactions" on public.transactions;
create policy "Users can update their transactions"
    on public.transactions for update
    to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their transactions" on public.transactions;
create policy "Users can delete their transactions"
    on public.transactions for delete
    to authenticated
    using ((select auth.uid()) = user_id);

revoke all on table public.transactions from anon;
grant select, insert, update, delete on table public.transactions to authenticated;
grant usage, select on sequence public.transactions_id_seq to authenticated;
